services:
  postgres:
    image: postgres:16
    container_name: postgres_biblioteca
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: posrtgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - biblioteca-network

networks:
  biblioteca-network:
    driver: "null"